export const ActionTypes = {
    'REGISTER_SUCCESS': 'REGISTER_SUCCESS',
    'REGISTER_FAIL': 'REGISTER_FAIL',
    'USER_LOADED': 'USER_LOADED',
    'AUTH_ERROR': 'AUTH_ERROR',
    'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
    'LOGOUT': 'LOGOUT',
    'LOGIN_FAIL': 'LOGIN_FAIL',
    'CLEAR_PROFILE': 'CLEAR_PROFILE',
    'ADMIN_SUCCESS': 'ADMIN_SUCCESS',
    'ADMIN_ERROR': 'ADMIN_ERROR'
}