export const ActionTypes = {
    'SHOW_COURSES': 'SHOW_COURSES',
    'SHOW_COURSES_ERROR': 'SHOW_COURSES_ERROR',
    'CREATE_COURSE': 'CREATE_COURSE',
    'CREATE_COURSE_ERROR': 'CREATE_COURSE_ERROR'
}