export const ActionTypes = {
    'SHOW_COURSES': 'SHOW_COURSES',
    'SHOW_COURSES_ERROR': 'SHOW_COURSES_ERROR',
    'CREATE_COURSE': 'CREATE_COURSE',
    'CREATE_COURSE_ERROR': 'CREATE_COURSE_ERROR',
    'DELETE_COURSE': 'DELETE_COURSE',
    'DELETE_COURSE_ERROR': 'DELETE_COURSE_ERROR',
    'UPDATE_COURSE': 'UPDATE_COURSE',
    'UPDATE_COURSE_FAIL': 'UPDATE_COURSE_FAIL',
    'SHOW_SINGLE_COURSE': 'SHOW_SINGLE_COURSE',
    'SHOW_SINGLE_COURSE_ERROR': 'SHOW_SINGLE_COURSE_ERROR'
}